# Generated by Django 3.1.1 on 2023-09-17 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_ptmeeting_student1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student1',
        ),
    ]
