# Generated by Django 3.1.1 on 2023-09-18 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_delete_student1'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptmeeting',
            name='date',
            field=models.DateField(default=datetime.date(2023, 9, 18)),
            preserve_default=False,
        ),
    ]
